baseURL = 'https://runningdigital.com'
languageCode = 'en-us'
title = 'RunningDigital'
theme = 'hugo-coder'
defaultcontentlanguage = "en"

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "David Hroncheck"
  # info = "Writer."
  # description = "-my personal website"
  # keywords = "blog,developer,personal"
  avatarurl = "/images/avatar.jpg"
  # gravatar = "john.doe@example.com"
  license = "MIT"
  favicon_32 = "/imgages/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2008

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 4
  url = "@runningdigital@mastodon.social"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:info@runningdigital.com"
 [[params.social]]
   name = "YouTube"
   icon = "fa fa-youtube-play fa-2x"
   weight = 3
   url = "https://youtube.com/runningdigital"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/runningdigital/"

# Menu links
# [[menu.main]]
#  name = "blog"
#  weight = 2
#  url  = "posts/"
[[menu.main]]
  name = "ABOUT"
  weight = 1
  url = "about/"
# [[menu.main]]
#  name = "recipes"
#  weight = 3
#  url = "recipes/"
